# Generated by Django 3.2.5 on 2021-07-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('admins', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'support',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tg_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('spec', models.CharField(blank=True, max_length=200, null=True)),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=200, null=True)),
                ('queue_number_static', models.IntegerField(blank=True, null=True)),
                ('queue_number', models.IntegerField(blank=True, null=True)),
                ('queue_status', models.CharField(blank=True, max_length=200, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('official_name', models.CharField(blank=True, max_length=200, null=True)),
                ('official_surname', models.CharField(blank=True, max_length=200, null=True)),
                ('official_patronymic', models.CharField(blank=True, max_length=200, null=True)),
                ('is_subscribed', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Gifs',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.DeleteModel(
            name='Texts',
        ),
    ]
